# SOPS Configuration Template
# 
# Before using this file:
# 1. Generate an age key: age-keygen -o ~/.config/sops/age/keys.txt
# 2. Get your public key: age-keygen -y ~/.config/sops/age/keys.txt
# 3. Replace YOUR_AGE_PUBLIC_KEY below with your actual public key
# 4. Remove this comment block
#
# Usage:
# - Create secrets: sops secrets/secrets.yaml
# - Edit secrets: sops secrets/secrets.yaml
# - Secrets are automatically encrypted/decrypted

keys:
  - &user_yawarakatai YOUR_AGE_PUBLIC_KEY  # Replace with: age1xxxxxxxxxx...

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *user_yawarakatai
