{ config, pkgs, vars, ... }:

{
  imports = [
    # Hardware configuration (auto-generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Shared base configuration (common settings for all hosts)
    ../../modules/system/base.nix

    # Core system modules
    ../../modules/system/boot.nix
    ../../modules/system/networking.nix
    ../../modules/system/locale.nix
    ../../modules/system/audio.nix
    ../../modules/system/zram.nix
    ../../modules/system/storage.nix
    ../../modules/system/rebuild-helper.nix
    ../../modules/system/wayland.nix
    ../../modules/system/niri-override.nix

    # Laptop-specific hardware modules
    ../../modules/system/touchpad.nix      # Touchpad with natural scrolling, tap-to-click
    ../../modules/system/bluetooth.nix     # Bluetooth support
    ../../modules/system/fingerprint.nix   # Fingerprint reader for login/sudo
    ../../modules/system/tlp.nix           # TLP power management for battery optimization
    ../../modules/system/webcam.nix        # Webcam support
  ];

  # Hostname
  networking.hostName = vars.hostname;

  # Host-specific user password
  # Password hash generated with: mkpasswd -m sha-512
  # Using same password hash as desuwa
  users.users.${vars.username}.hashedPassword = "$6$KtMQPtEMmQ9AW7qK$tvtWeUA5GzWyILnexkH51.OMTnM6cuzA2aEymac264HctHr5jRBH7NBOOn4twZqaF963f8KkgDdNzfpSfd54D0";

  # Add user to video group for webcam access
  users.users.${vars.username}.extraGroups = [ "video" ];

  # Host-specific Nix settings (extends base.nix)
  nix.settings = {
    # Add Vicinae cache for this host
    substituters = [
      "https://vicinae.cachix.org"
    ];
    trusted-public-keys = [
      "vicinae.cachix.org-1:1kDrfienkGHPYbkpNj1mWTr7Fm1+zcenzgTizIcI3oc="
    ];
  };

  # State version - DO NOT CHANGE after initial install
  system.stateVersion = "25.05";
}
