{ config, pkgs, vars, inputs, ... }:

{

  imports = [

    inputs.nixos-hardware.nixosModules.lenovo-thinkpad-x1-nano

    # Hardware configuration (auto-generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Shared base configuration (common settings for all hosts)
    ../../modules/system/base.nix

    # Core system modules
    ../../modules/system/boot.nix
    ../../modules/system/networking.nix
    ../../modules/system/locale.nix
    ../../modules/system/audio.nix
    ../../modules/system/zram.nix
    ../../modules/system/storage.nix
    ../../modules/system/rebuild-helper.nix
    ../../modules/system/wayland.nix
    ../../modules/system/niri-override.nix

    # Laptop-specific hardware modules
    ../../modules/system/touchpad.nix # Touchpad with natural scrolling, tap-to-click
    ../../modules/system/bluetooth.nix # Bluetooth support
    ../../modules/system/fingerprint.nix # Fingerprint reader for login/sudo
    ../../modules/system/tlp.nix # TLP power management for battery optimization
    ../../modules/system/webcam.nix # Webcam support
  ];

  # Workaround for Alder Lake audio firmware signature verification failure
  # Use legacy HDA driver instead of SOF until firmware is properly signed
  # dsp_driver: 1=legacy HDA, 3=SOF (Smart Sound)
  boot.kernelParams = [
    "snd_intel_dspcfg.dsp_driver=1"
  ];

  # Hostname
  networking.hostName = vars.hostname;

  # Host-specific user password
  # Password hash generated with: mkpasswd -m sha-512
  users.users.${vars.username}.hashedPassword = "$6$KtMQPtEMmQ9AW7qK$tvtWeUA5GzWyILnexkH51.OMTnM6cuzA2aEymac264HctHr5jRBH7NBOOn4twZqaF963f8KkgDdNzfpSfd54D0";

  # Host-specific Nix settings (extends base.nix)
  nix.settings = { };

  services.logind.settings.Login = {
    HandleLidSwitch = "suspend";
    HandleLidSwitchDocked = "suspend";
    HandleLidSwitchExternalPower = "suspend";
  };

  # State version - DO NOT CHANGE after initial install
  system.stateVersion = "25.05";
}
