# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

let
  btrfsOpts = [ "compress=zstd" "noatime" ];
in
{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/663c8bf1-5235-46ea-93e8-45a66800a1f7";
      fsType = "btrfs";
      options = [ "subvol=@" ] ++ btrfsOpts;
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/663c8bf1-5235-46ea-93e8-45a66800a1f7";
      fsType = "btrfs";
      options = [ "subvol=@home" ] ++ btrfsOpts;
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/663c8bf1-5235-46ea-93e8-45a66800a1f7";
      fsType = "btrfs";
      options = [ "subvol=@nix" ] ++ btrfsOpts;
    };

  fileSystems."/var/log" =
    {
      device = "/dev/disk/by-uuid/663c8bf1-5235-46ea-93e8-45a66800a1f7";
      fsType = "btrfs";
      options = [ "subvol=@log" ] ++ btrfsOpts;
    };

  fileSystems."/var/cache" =
    {
      device = "/dev/disk/by-uuid/663c8bf1-5235-46ea-93e8-45a66800a1f7";
      fsType = "btrfs";
      options = [ "subvol=@cache" ] ++ btrfsOpts;
    };

  fileSystems."/tmp" =
    {
      device = "/dev/disk/by-uuid/663c8bf1-5235-46ea-93e8-45a66800a1f7";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ] ++ btrfsOpts;
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/0474-E13D";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
